name: Tự động Deploy lên cPanel

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Tải code từ GitHub về máy ảo
      uses: actions/checkout@v3

    - name: 🛠️ Cài đặt Node.js và Build Vue 3
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: Chạy lệnh Build Vue và Chuyển file
      run: |
        cd frontend 
        npm install
        npm run build
        # Lệnh cực kỳ quan trọng: Copy toàn bộ ruột của dist ra ngoài thư mục gốc
        cp -r dist/* ../

    - name: 🚀 Đẩy code lên cPanel qua FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ./
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/frontend/** **/.github/**
          readme.md